apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-ansible-delegate
  namespace: harness-delegate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harness-ansible-delegate
  template:
    metadata:
      labels:
        app: harness-ansible-delegate
    spec:
      serviceAccountName: harness-delegate-sa
      containers:
        - name: harness-ansible-delegate
          image: 650251703160.dkr.ecr.us-east-1.amazonaws.com/harness-delegate-ansible
          env:
            - name: DELEGATE_NAME
              value: "terraform-delegate"
            - name: ACCOUNT_ID
              value: "axO8S93qRGqqf1tlBaonnQ"
            - name: DELEGATE_TOKEN
              value: "OWYyNDYzMjVlODVkZTJlY2RiZmFlZjM2NmEzMDk3N2Y="
            - name: AWS_REGION
              value: "us-west-1"
          volumeMounts:
            - name: ansible-inventory
              mountPath: /etc/ansible/hosts
              subPath: inventory
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "/harness/rollback.sh"]
      volumes:
        - name: ansible-inventory
          emptyDir: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: harness-delegate-sa
  namespace: harness-delegate
