apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-delegate
  namespace: harness-delegate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harness-delegate
  template:
    metadata:
      labels:
        app: harness-delegate
        harness.io/selector: terraform-delegate  # Ensure selector is set
    spec:
      containers:
        - name: delegate
          image: 650251703160.dkr.ecr.us-east-1.amazonaws.com/harness-delegate-ansible
          env:
            - name: ACCOUNT_ID
              value: "axO8S93qRGqqf1tlBaonnQ"
            - name: DELEGATE_TOKEN
              value: "OWYyNDYzMjVlODVkZTJlY2RiZmFlZjM2NmEzMDk3N2Y="
