- name: Configure EKS Nodes with Ansible
  hosts: eks_nodes
  become: yes
  tasks:
    - name: Install required packages
      yum:
        name: ['docker', 'git']
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install and Start Nginx on EKS Nodes
      yum:
        name: nginx
        state: present

    - name: Start Nginx
      service:
        name: nginx
        state: started

    - name: Verify Nginx is Running
      command: systemctl status nginx
      register: nginx_status
      failed_when: "'running' not in nginx_status.stdout"
